=== ija1/Phase_1/Phase1/Aufgabe3_C.xsd
<?xml version="1.0" encoding="UTF-8"?>    
<xsd:schema attributeFormDefault="unqualified" 
            elementFormDefault="qualified" version="1.0" 
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="rezepte" type="rezepteType" />
  <xsd:complexType name="rezepteType">
    <xsd:sequence>
      <xsd:element name="rezept" type="rezeptType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="rezeptType">
    <xsd:sequence>
      <xsd:element name="rezeptname" type="xsd:string" />
      <xsd:element name="zutaten" type="zutatenType" />
      <xsd:element name="zubereitung" type="zubereitungType" />
      <xsd:element name="kommentare" type="kommentareType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:int" />
  </xsd:complexType>
  <xsd:complexType name="kommentareType">
    <xsd:sequence>
      <xsd:element name="user" type="xsd:string" />
      <xsd:element name="datum" type="xsd:date" />
      <xsd:element name="text" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="zubereitungType">
    <xsd:sequence>
      <xsd:element name="arbeitszeit" type="arbeitszeitType" />
      <xsd:element name="schwierigkeitsgrad" type="xsd:string" />
      <xsd:element name="kalorien" type="xsd:int" />
      <xsd:element name="portion" type="xsd:int" />
      <xsd:element name="beschreibung" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="arbeitszeitType">
    <xsd:sequence>
      <xsd:element name="stunde" type="xsd:int" />
      <xsd:element name="minuten" type="xsd:int" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="zutatenType">
    <xsd:sequence>
      <xsd:element maxOccurs="unbounded" name="zutat" type="zutatType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="zutatType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" />
      <xsd:element name="menge" type="xsd:positiveInteger" />
      <xsd:element name="einheit" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== ija1/Phase_1/Phase1/Testdaten2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3_C.xsd">
  <rezept id="0">
    <rezeptname>Gefüllte Paprika</rezeptname>
    <zutaten>
      <zutat>
        <name>Parika</name>
        <menge>3</menge>
        <einheit>0</einheit>
      </zutat>
      <zutat>
        <name>Hackfleisch</name>
        <menge>300</menge>
        <einheit>g</einheit>
      </zutat>
    </zutaten>
    <zubereitung>
      <arbeitszeit>
        <stunde>1</stunde>
        <minuten>10</minuten>
      </arbeitszeit>
      <schwierigkeitsgrad>normal</schwierigkeitsgrad>
      <kalorien>540</kalorien>
      <portion>6</portion>
      <beschreibung>Hackfleisch würzen und die Parikas damit füllen</beschreibung>
    </zubereitung>
    <kommentare>
      <user>sweetheart</user>
      <datum>2013-07-09</datum>
      <text>In Tomatensosse schmeckt es noch besser</text>
    </kommentare>
  </rezept>
</rezepte>

=== ija1/Phase_1/Phase1/Testdaten1.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3_C.xsd">
  <rezept>
    <rezeptname>Schupfnudel</rezeptname>
    <zutaten>
      <zutat>
        <name>Schupfnudel</name>
        <menge>1</menge>
        <einheit>Pck</einheit>
      </zutat>
    </zutaten>
    <zubereitung>
      <arbeitszeit>
        <stunde>0</stunde>
        <minuten>10</minuten>
      </arbeitszeit>
      <schwierigkeitsgrad>normal</schwierigkeitsgrad>
      <kalorien>150</kalorien>
      <portion>2</portion>
      <beschreibung>Schupfnudel mit Butter in eine Pfanne geben und braten
      				bis dies goldbraun sind.
      </beschreibung>
    </zubereitung>
    <kommentare>
      <user>schneehase</user>
      <datum>2012-02-13</datum>
      <text>Ganz einfach und lecker</text>
    </kommentare>
  </rezept>
  </rezepte>
